name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    env:
      Solution_Name: win-cursor-splasher.sln
      Test_Project_Path: win-cursor-splasher.csproj

    steps:

    - uses: actions/checkout@master
    - uses: microsoft/setup-msbuild@v2
    - uses: nuget/setup-nuget@v2

    - run: nuget restore $env:Solution_Name
    - run: msbuild $env:Solution_Name /p:Configuration=Release /p:DeployOnBuild=true /p:PublishProfile=FolderProfile
    - run: tree /f

    - uses: actions/upload-artifact@v4
      with:
        name: release
        path: bin\Release
